name: PyTest

on:
  push:
  workflow_dispatch:   # Adds "Run workflow" button in Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NAVIGATOR_API_KEY: ${{ secrets.NAVIGATOR_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v4
      - run: uv sync
      - run: uv run pytest -v
